version: "3.7"

services:
  npm:
    image: node:18.15.0
    container_name: primarybyte-npm
    entrypoint: npm
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      REDIS_DSN: "redis://redis:6379/0"
    working_dir: /opt/primarybyte
    volumes:
      - .:/opt/primarybyte
    profiles:
      - npm

  app:
    image: node:18.15.0
    container_name: primarybyte-app
    command: npm run local
    environment:
      APP_HOST: "0.0.0.0"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      REDIS_DSN: "redis://redis:6379/0"
    ports:
      - ${EXTERNAL_APP_PORT}:${APP_PORT}
    working_dir: /opt/primarybyte
    volumes:
      - .:/opt/primarybyte
    profiles:
      - app
    depends_on:
      - mysql
      - redis

  app-debug:
    image: node:18.15.0
    container_name: primarybyte-app
    command: npm run local:debug
    environment:
      APP_HOST: "0.0.0.0"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      REDIS_DSN: "redis://redis:6379/0"
    ports:
      - ${EXTERNAL_APP_PORT}:${APP_PORT}
      - ${EXTERNAL_APP_DEBUG_PORT}:9229
    working_dir: /opt/primarybyte
    volumes:
      - .:/opt/primarybyte
    profiles:
      - app-debug
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0.32
    container_name: primarybyte-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql
    ports:
      - ${EXTERNAL_MYSQL_PORT}:3306
    profiles:
      - infra

  redis:
    image: redis:7.0.10
    container_name: primarybyte-redis
    ports:
      - ${EXTERNAL_REDIS_PORT}:6379
    profiles:
      - infra
